version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/app
      - ./docker/nginx/retailcrm-googlecalendar.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:${NGINX_HTTP_PORT}

  php-fpm:
    volumes:
      - .:/app
